name: crm_mrs_app
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.2.6 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

 # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^1.0.2
  motion_tab_bar_v2: ^0.3.0
  shrink_sidemenu: ^2.0.0+2-null-safety
  pie_chart: ^5.3.2
  dropdown_textfield: ^1.0.8
  http: ^1.1.0
  provider: ^6.0.1
  fluttertoast: ^8.1.1
  date_format: ^2.0.7
  shared_preferences: ^2.2.0
  marqueer: ^1.4.0
  scroll_snap_list: ^0.9.1
  custom_clippers: ^2.0.0
  flutter_dash: ^1.0.0
  dotted_border: ^2.0.0+3
  overlay_loader_with_app_icon: ^0.0.3
  flutter_html: ^3.0.0-beta.2
  html: ^0.15.4
  intl: ^0.18.1
  awesome_dialog: ^3.1.0
  image_picker: ^1.0.4
  file: ^6.1.4
  geolocator: ^7.0.3
  file_picker: ^5.5.0
  url_launcher: ^6.2.3
  dio: 
  flutter_widget_from_html: ^0.10.4
  shimmer: ^3.0.0
  animated_text_kit:
  flutter_phone_direct_caller: 
  flutter_rating_bar: 
  group_button: ^5.3.4
  intl_phone_field: 
  syncfusion_flutter_pdfviewer: ^23.1.38
  path: ^1.8.3
  # package_info: ^2.0.2
  package_info_plus: ^4.2.0
  network_info_plus: ^4.1.0
  photo_view: ^0.14.0
  video_player: ^2.4.12
  insta_image_viewer: ^1.0.2
  flutter_media_downloader: ^1.0.2
  responsive_sizer:
  get:
  get_storage:
  upgrader: ^8.3.0
  # connectivity: ^3.0.6
  connectivity_plus: ^6.0.5
  logger: ^2.0.2+1
  async: ^2.11.0
  carousel_slider: ^5.0.0

dev_dependencies:
  flutter_launcher_icons: "^0.13.1"
  flutter_test:
    sdk: flutter

flutter_icons:
  android: true
  ios: true
  image_path: "assets/icons/app_icon.png"
 


  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
  assets:
 
    - assets/icons/app_icon.png
    - assets/images/ic_search.png
    
    
  
 

  
  
 
  
    
  

   
